### ISSUE TITLE
Nodejs example currently not working for node 10

### ISSUE THREAD

**Issue by kkdai** [line/line-simple-beacon#7]
Hi 

I have tried it and found out it has the problem with node 10

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'xpc-connection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Evan/src/go/src/github.com/kkdai/line-simple-beacon/tools/line-simplebeacon-nodejs-sample/node_modules/bleno/lib/mac/highsierra.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

So, I try to downgrade to node@8 it works well.

**Comment by yohsuke** [comment]
Thank you for your information.
As you said, now we cannot use our program on node@10.
It seems to be occurred by `xpc-connection` issue.

Currently not fixed yet, so I'll add notes about it to our Readme.

**Comment by yohsuke** [comment]
I added the notes about this version issue on our Readme.
And we'll monitor the library update.
Thanks.
